apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-deployment
spec:
  replicas: 3 # Adjust the number of replicas as per your requirements
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: gcr.io/gestion-formation-3/django:latest
          ports:
            - containerPort: 8000 # Adjust the container port as per your Django app's configuration
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "gestion_formation.settings" # Specify your Django app's settings module
