# Generated by Django 4.1.7 on 2023-03-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_salle', models.CharField(max_length=50)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('horraire', models.TimeField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
