# Generated by Django 4.1.7 on 2023-03-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_formateur_rename_horraire_formation_horraire_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.formateur'),
        ),
    ]
