# Generated by Django 4.1.7 on 2023-03-24 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_participant_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
