# Generated by Django 4.1 on 2023-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_participant_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images-formation'),
        ),
    ]
