# Generated by Django 4.1 on 2023-03-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_formation_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='horraire_fin',
        ),
    ]
