# Generated by Django 4.1 on 2023-03-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_formation_horraire_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(blank=True, to='base.participant'),
        ),
    ]
