# Generated by Django 4.1 on 2023-03-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_formation_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images-formation'),
        ),
    ]
