# Generated by Django 4.1 on 2023-04-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_formateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
