# Generated by Django 4.1 on 2023-04-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_formation_max_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='max_place',
            new_name='max_places',
        ),
    ]
