# Generated by Django 4.1 on 2023-04-02 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_participant_nom_remove_participant_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cin',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
