# Generated by Django 4.1 on 2023-04-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_participant_user_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='participant',
        ),
        migrations.AddField(
            model_name='participant',
            name='formations',
            field=models.ManyToManyField(blank=True, to='base.formation'),
        ),
    ]
