# Generated by Django 4.1 on 2023-04-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_formation_participant_participant_formations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='formations',
        ),
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(to='base.participant'),
        ),
    ]
