# Generated by Django 4.1 on 2023-04-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_participant_formations_formation_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(blank=True, null=True, to='base.participant'),
        ),
    ]
