# Generated by Django 4.1 on 2023-04-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(blank=True, to='base.participant'),
        ),
    ]
