# Generated by Django 4.1 on 2023-04-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['timestamp']},
        ),
    ]
