# Generated by Django 4.1 on 2023-04-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
    ]
