# Generated by Django 4.1 on 2023-04-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
