# Generated by Django 4.1 on 2023-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_formateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='domaine',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
