# Generated by Django 4.1 on 2023-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_formateur_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/az.jpg', null=True, upload_to='images-formation'),
        ),
    ]
