# Generated by Django 4.1 on 2023-06-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_formation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formateur',
            name='nom',
            field=models.CharField(max_length=70),
        ),
    ]
